### ISSUE TITLE
KeyError: 'san_usec_per_read_op' and 'san_usec_per_write_op'

### ISSUE THREAD

**Issue by Acmosa** [jeremyverda/zabbix-public#3]
arraySanUsecPerReadOp = str(arrayValues["san_usec_per_read_op"])
arraySanUsecPerWriteOp = str(arrayValues["san_usec_per_write_op"])

Both generate Key Error with Pure Storage Purity 4.8.12 
Disabling them in PureArrayMonitor.py and PureVolumeMonitor.py makes the scripts work.

Thanks for your great work on these scripts! :)

**Comment by jeremyverda** [comment]
Thanks for your feedback.
We are currently using 4.10.8 so it seems those keys are new.
I'm currently working on a new version with more information since we are on production.
I will take care of those errors by checking all keys presence before sending them.

Have a great day!

**Comment by jeremyverda** [comment]
Hello,

Thanks for your patience.
This issue should be solved in the new version. More information available here : https://jeremyverda.net/zabbix-and-pure-storage-monitoring-v2/
