### ISSUE TITLE
MTR

### ISSUE THREAD

**Issue by qooke** [jeremyverda/zabbix-public#4]
Usually I just tell the owner if they are up or down. But recently, I have encountered some network problems and it is difficult to know what happened and whether the problem is with me or the data center site.

Nothing special, add host, use iccmping value (fping) and return 1 and 0

Then trigger the activation operation and I receive an email

But is there any option or procedure to automatically send zabbix to host mtr and send it to email?

**Comment by jeremyverda** [comment]
Hello,

Let me know if I understand your question : 
In case of a icmp issue, you would like to start a traceroute and send the result by e-mail?

Thanks.

**Comment by qooke** [comment]
![qq](https://user-images.githubusercontent.com/31933126/41137062-d5752d90-6b0b-11e8-8d46-eb0ecdfec77b.png)
Send a result like this so that at a glance you know where to drop or break
