### ISSUE TITLE
XML Problem

### ISSUE THREAD

**Issue by Arnros** [jeremyverda/zabbix-public#5]
Hi

Thanks for your Zabbix Template.

I've a problem when I upload XML on zabbix 4.0.1 (I dont have on 3.4).

````
Cannot read XML: (68) StartTag: invalid element name [Line: 2695 | Column: 2].
````

Thanks for your help.

**Comment by jeremyverda** [comment]
Hello,

The issue should be fixed in the file.
There was some content due to a bad export or a bad merge in git.

Sorry for the issue.

**Comment by Arnros** [comment]
Thanks for your update. It's OK now.
