### ISSUE TITLE
volumeMonitoring timing out

### ISSUE THREAD

**Issue by tmroberts-tableau** [jeremyverda/zabbix-public#7]
I have the timeout parameter set to 30 seconds on the zabbix server thinking that that was the problem, but when i tried to run the script with the volumeMonitoring parameters it runs for quite a while before it returns a 1.  Far longer than the timeout setting in Zabbix allows for.  Any idea if this is a script issue or a system issue?

**Comment by jeremyverda** [comment]
Hello,

Sorry for the delay, I completely missed this issue.
If this issue is with the V2 of this script, I've seen it when there is a lot of volumes on the array.

How many volumes do you have?
